//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace regs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        
        public int Id { get; set; }

        [Required(ErrorMessage ="Please Enter Your First Name")]
        public string Firstname { get; set; }

        [Required(ErrorMessage = "Please Enter Your Last Name")]
        public string Lastname { get; set; }

        [Required(ErrorMessage = "Please Enter Your Mobile Number")]
        [DataType(DataType.PhoneNumber)]
        public string Mobile { get; set; }

        [Required(ErrorMessage = "Please Enter Your Mail-Id")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [Display(Name = "Re-enter Password")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string Cpassword { get; set; }

        [Required(ErrorMessage = "Please Enter Your Profile")]
        public string Profile { get; set; }

        [Required (ErrorMessage = "Please Select The Gender")]
        public string Gender { get; set; }
    }
}
