//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcnew.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Trainee()
        {
            this.student_result = new HashSet<student_result>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public System.DateTime dob { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_result> student_result { get; set; }
        public virtual Student_Trainee Student_Trainee1 { get; set; }
        public virtual Student_Trainee Student_Trainee2 { get; set; }
    }
}
